package com.live.holyquranmp3.quran;

import android.content.Context;
import android.os.Environment;
import android.os.Handler;
import android.os.Looper;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;

public class LnaguageClass {

    public interface SurahListListener {
        void onSurahListReady(List<AuthorClass> surahs);
    }

    private static final List<AuthorClass> ALL_AUTHORS_ARABIC;
    private static final List<AuthorClass> ALL_AUTHORS_ENGLISH;
    private static final List<AuthorClass> ALL_SURAS_ARABIC;
    private static final List<AuthorClass> ALL_SURAS_ENGLISH;

    static {
        ArrayList<AuthorClass> arabicAuthors = new ArrayList<>();
        arabicAuthors.add(new AuthorClass("shatri", "أبو بكر الشاطري"));
        arabicAuthors.add(new AuthorClass("afs", "مشاري العفاسي"));
        arabicAuthors.add(new AuthorClass("a_jbr", "علي جابر"));
        arabicAuthors.add(new AuthorClass("shur", "سعود الشريم"));
        arabicAuthors.add(new AuthorClass("s_gmd", "سعد الغامدي"));
        arabicAuthors.add(new AuthorClass("sds", "عبدالرحمن السديس"));
        arabicAuthors.add(new AuthorClass("maher", "ماهر المعيقلي"));
        arabicAuthors.add(new AuthorClass("basit", "عبدالباسط عبدالصمد"));
        arabicAuthors.add(new AuthorClass("omar_warsh", "عمر القزابري (رواية ورش عن نافع)"));
        arabicAuthors.add(new AuthorClass("yasser", "ياسر الدوسري"));
        arabicAuthors.add(new AuthorClass("qtm", "ناصر القطامي"));
        arabicAuthors.add(new AuthorClass("ajm", "أحمد بن علي العجمي"));
        arabicAuthors.add(new AuthorClass("hthfi", "علي الحذيفي"));
        arabicAuthors.add(new AuthorClass("huthifi_qalon", "علي الحذيفي (رواية قالون)"));
        arabicAuthors.add(new AuthorClass("minsh", "محمد صديق المنشاوي"));

        arabicAuthors.add(new AuthorClass("nufais/Rewayat-Hafs-A-n-Assem", "أحمد النفيس"));
        arabicAuthors.add(new AuthorClass("shaheen/Rewayat-Hafs-A-n-Assem", "أحمد خليل شاهين"));
        arabicAuthors.add(new AuthorClass("shamsan/Rewayat-Hafs-A-n-Assem", "الوليد الشمسان"));
        arabicAuthors.add(new AuthorClass("a_maasaraawi/Rewayat-Hafs-A-n-Assem", "أحمد عيسى المعصراوي"));
        arabicAuthors.add(new AuthorClass("islam/Rewayat-Hafs-A-n-Assem", "إسلام صبحي"));
        arabicAuthors.add(new AuthorClass("kurdi", "رعد محمد الكردي"));
        arabicAuthors.add(new AuthorClass("wdee3", "وديع اليمني"));
        arabicAuthors.add(new AuthorClass("hazza", "هزاع البلوشي"));





        arabicAuthors.add(new AuthorClass("s_bud", "صلاح البدير"));
        arabicAuthors.add(new AuthorClass("frs_a", "فارس عباد"));
        arabicAuthors.add(new AuthorClass("bu_khtr", "صلاح بو خاطر"));
        arabicAuthors.add(new AuthorClass("ayyub", "محمد أيوب"));
        arabicAuthors.add(new AuthorClass("husr", "محمود خليل الحصري"));
        arabicAuthors.add(new AuthorClass("ra3ad", "مصطفى رعد العزاوي"));
        arabicAuthors.add(new AuthorClass("twfeeq", "توفيق الصايغ"));
        arabicAuthors.add(new AuthorClass("koshi", "العيون الكوشي"));
//        arabicAuthors.add(new AuthorClass("bna_mjwd", "محمود علي البنا"));
        arabicAuthors.add(new AuthorClass("taher", "شيرزاد عبدالرحمن طاهر"));
        arabicAuthors.add(new AuthorClass("tblawi", "محمد الطبلاوي"));
        arabicAuthors.add(new AuthorClass("yahya", "يحيى حوا"));
        arabicAuthors.add(new AuthorClass("jbrl", "محمد جبريل"));
        arabicAuthors.add(new AuthorClass("abkr", "إدريس أبكر"));
        arabicAuthors.add(new AuthorClass("tnjy", "خليفة الطنيجي"));
        arabicAuthors.add(new AuthorClass("bari", "عبدالبارئ محمد"));
        arabicAuthors.add(new AuthorClass("jbreen", "إبراهيم الجبرين"));
        arabicAuthors.add(new AuthorClass("ahmad_nu", "أحمد نعينع"));
        arabicAuthors.add(new AuthorClass("mohna", "خالد المهنا"));
        arabicAuthors.add(new AuthorClass("sami_dosr", "سامي الدوسري"));
        arabicAuthors.add(new AuthorClass("trabulsi", "أحمد الطرابلسي"));
        arabicAuthors.add(new AuthorClass("trablsi", "أحمد الطرابلسي (رواية قالون)"));
        arabicAuthors.add(new AuthorClass("bsfr", "عبدالله بصفر"));
        arabicAuthors.add(new AuthorClass("soufi_klf", "عبدالرشيد صوفي"));
        arabicAuthors.add(new AuthorClass("jhn", "عبدالله عواد الجهني"));
        arabicAuthors.add(new AuthorClass("kyat", "عبدالله خياط"));
        arabicAuthors.add(new AuthorClass("sahood", "صالح الصاهود"));
        arabicAuthors.add(new AuthorClass("akil", "أخيل عبدالحي روا"));
        arabicAuthors.add(new AuthorClass("mustafa", "مصطفى إسماعيل"));
        arabicAuthors.add(new AuthorClass("braak", "محمد البراك"));
        arabicAuthors.add(new AuthorClass("Abdullahk", "عبدالله الكندري"));
        arabicAuthors.add(new AuthorClass("mtrod", "عبدالله المطرود"));
        arabicAuthors.add(new AuthorClass("qht", "خالد القحطاني"));
        arabicAuthors.add(new AuthorClass("a_klb", "عادل الكلباني"));
        arabicAuthors.add(new AuthorClass("akdr", "إبراهيم الأخضر"));
        arabicAuthors.add(new AuthorClass("IbrahemSadan", "إبراهيم السعدان"));
        arabicAuthors.add(new AuthorClass("qari", "القارئ ياسين"));
        arabicAuthors.add(new AuthorClass("hawashi", "أحمد الحواشي"));
        arabicAuthors.add(new AuthorClass("ahmad_huth", "أحمد الحذيفي"));
        arabicAuthors.add(new AuthorClass("saud", "أحمد سعود"));
        arabicAuthors.add(new AuthorClass("saber", "أحمد صابر"));
        arabicAuthors.add(new AuthorClass("Aamer", "أحمد عامر"));
        arabicAuthors.add(new AuthorClass("jormy", "ابراهيم الجرمي"));
        arabicAuthors.add(new AuthorClass("akrm", "أكرم العلاقمي"));
        arabicAuthors.add(new AuthorClass("fateh", "الفاتح محمد الزبير"));
        arabicAuthors.add(new AuthorClass("jaman", "جمعان العصيمي"));
        arabicAuthors.add(new AuthorClass("kafi", "خالد عبدالكافي"));
        arabicAuthors.add(new AuthorClass("tareq", "طارق عبدالغني دعوب"));
        arabicAuthors.add(new AuthorClass("jamal", "جمال شاكر عبدالله"));
        arabicAuthors.add(new AuthorClass("thubti", "عبدالبارئ الثبيتي"));
//        arabicAuthors.add(new AuthorClass("mohsin_harthi", "عبدالمحسن الحارثي"));
        arabicAuthors.add(new AuthorClass("mhsny", "محمد المحيسني"));
        arabicAuthors.add(new AuthorClass("nabil", "نبيل الرفاعي"));
        arabicAuthors.add(new AuthorClass("a_ahmed", "عبدالعزيز الأحمد"));
        arabicAuthors.add(new AuthorClass("kanakeri", "عبدالهادي أحمد كناكري"));
        arabicAuthors.add(new AuthorClass("mrifai", "محمود الرفاعي"));
        arabicAuthors.add(new AuthorClass("obk", "عبدالمحسن العبيكان"));
        arabicAuthors.add(new AuthorClass("monshed", "محمد المنشد"));
        arabicAuthors.add(new AuthorClass("namh", "نعمة الحسان"));
        arabicAuthors.add(new AuthorClass("hani", "هاني الرفاعي"));
        arabicAuthors.add(new AuthorClass("3zazi", "الحسيني العزازي"));
        arabicAuthors.add(new AuthorClass("qasm", "عبدالمحسن القاسم"));
        arabicAuthors.add(new AuthorClass("khan", "محمد عثمان خان"));
        arabicAuthors.add(new AuthorClass("abdullah_dori", "محمد عبدالحكيم"));
        arabicAuthors.add(new AuthorClass("shaksh", "ماهر شخاشيرو"));
        arabicAuthors.add(new AuthorClass("mzroyee", "ياسر المزروعي"));
        arabicAuthors.add(new AuthorClass("muftah_thakwan", "مفتاح السلطني"));
        arabicAuthors.add(new AuthorClass("waleed", "وليد النائحي"));
        arabicAuthors.add(new AuthorClass("lahoni", "مصطفى اللاهوني"));
        arabicAuthors.add(new AuthorClass("zaml", "ماجد الزامل"));
        arabicAuthors.add(new AuthorClass("abo_hashim", "علي أبو هاشم"));
        arabicAuthors.add(new AuthorClass("dokali", "الدوكالي محمد العالم"));
        arabicAuthors.add(new AuthorClass("harthi", "معيض الحارثي"));
        arabicAuthors.add(new AuthorClass("sayed", "سيد رمضان"));
        arabicAuthors.add(new AuthorClass("qurashi", "ياسر القرشي"));
        arabicAuthors.add(new AuthorClass("brmi", "عبدالله البريمي"));
        arabicAuthors.add(new AuthorClass("rashad", "محمد رشاد الشريف"));
        arabicAuthors.add(new AuthorClass("yousef", "يوسف الشويعي"));
        arabicAuthors.add(new AuthorClass("3siri", "ابراهيم العسيري"));
        arabicAuthors.add(new AuthorClass("noah", "يوسف بن نوح أحمد"));
        arabicAuthors.add(new AuthorClass("zamri", "استاذ زامري"));
        arabicAuthors.add(new AuthorClass("zaki", "زكي داغستاني"));
        arabicAuthors.add(new AuthorClass("alzain", "الزين محمد أحمد"));
        arabicAuthors.add(new AuthorClass("omran", "العشري عمران"));
        arabicAuthors.add(new AuthorClass("hatem", "حاتم فريد الواع"));
        arabicAuthors.add(new AuthorClass("hamza", "داود حمزة"));
        arabicAuthors.add(new AuthorClass("ifrad", "رشيد إفراد"));
        arabicAuthors.add(new AuthorClass("shl", "سهل ياسين"));
        arabicAuthors.add(new AuthorClass("hkm", "صابر عبدالحكم"));
        arabicAuthors.add(new AuthorClass("salah_hashim_m", "صلاح الهاشم"));
        arabicAuthors.add(new AuthorClass("ryan", "عادل ريان"));
        arabicAuthors.add(new AuthorClass("wdod", "عبدالودود حنيف"));
        arabicAuthors.add(new AuthorClass("hajjaj", "علي حجاج السويسي"));
        arabicAuthors.add(new AuthorClass("hafz", "عماد زهير حافظ"));
        arabicAuthors.add(new AuthorClass("lafi", "لافي العوني"));
        arabicAuthors.add(new AuthorClass("shaibat", "مالك شيبة الحمد"));
        arabicAuthors.add(new AuthorClass("shah", "محمد صالح"));
        arabicAuthors.add(new AuthorClass("sheimy", "محمود الشيمي"));
        arabicAuthors.add(new AuthorClass("bilal", "موسى بلال"));
        ALL_AUTHORS_ARABIC = Collections.unmodifiableList(arabicAuthors);

        ArrayList<AuthorClass> englishAuthors = new ArrayList<>();
        englishAuthors.add(new AuthorClass("shatri", "Abu Bakr Al-Shatri"));
        englishAuthors.add(new AuthorClass("afs", "Mishary Al-Afasy"));
        englishAuthors.add(new AuthorClass("a_jbr", "Ali Jaber"));
        englishAuthors.add(new AuthorClass("shur", "Saud Al-Shuraim"));
        englishAuthors.add(new AuthorClass("s_gmd", "Saad Al-Ghamdi"));
        englishAuthors.add(new AuthorClass("sds", "Abd Al-Rahman Al-Sudais"));
        englishAuthors.add(new AuthorClass("maher", "Maher Al-Meaqli"));
        englishAuthors.add(new AuthorClass("basit", "Abd Al-Basit Abd Al-Samad"));
        englishAuthors.add(new AuthorClass("omar_warsh", "Omar Al-Qazabri (Rewayat Warsh)"));
        englishAuthors.add(new AuthorClass("yasser", "Yasser Al-Dosari"));
        englishAuthors.add(new AuthorClass("qtm", "Nasser Al-Qatami"));
        englishAuthors.add(new AuthorClass("ajm", "Ahmad bin Ali Al-Ajmi"));
        englishAuthors.add(new AuthorClass("hthfi", "Ali Al-Huthaifi"));
        englishAuthors.add(new AuthorClass("huthifi_qalon", "Ali Al-Huthaifi (Rewayat Qalon)"));
        englishAuthors.add(new AuthorClass("minsh", "Mohammed Siddiq Al-Minshawi"));
        englishAuthors.add(new AuthorClass("nufais/Rewayat-Hafs-A-n-Assem", "Ahmad Alnufais"));
        englishAuthors.add(new AuthorClass("shaheen/Rewayat-Hafs-A-n-Assem", "Ahmad Khalil Shaheen"));
        englishAuthors.add(new AuthorClass("shamsan/Rewayat-Hafs-A-n-Assem", "Waleed Al-Shamsan"));
        englishAuthors.add(new AuthorClass("a_maasaraawi/Rewayat-Hafs-A-n-Assem", "Ahmad Essa El-Masarawi"));
        englishAuthors.add(new AuthorClass("islam/Rewayat-Hafs-A-n-Assem", "Islam Sobhi"));
        englishAuthors.add(new AuthorClass("kurdi", "Raad Mohammad Al-Kurdi"));
        englishAuthors.add(new AuthorClass("wdee3", "Wadee' Hammadi Al-Yamani"));
        englishAuthors.add(new AuthorClass("hazza", "Hazza Al-Balushi"));



        englishAuthors.add(new AuthorClass("s_bud", "Salah Al-Budair"));
        englishAuthors.add(new AuthorClass("frs_a", "Fares Abbad"));
        englishAuthors.add(new AuthorClass("bu_khtr", "Salah Bukhatir"));
        englishAuthors.add(new AuthorClass("ayyub", "Mohammed Ayyub"));
        englishAuthors.add(new AuthorClass("husr", "Mahmoud Khalil Al-Hussary"));
        englishAuthors.add(new AuthorClass("ra3ad", "Mustafa Raad Al-Azawy"));
        englishAuthors.add(new AuthorClass("twfeeq", "Tawfeeq As-Sayegh"));
        englishAuthors.add(new AuthorClass("koshi", "Al-Oyoon Al-Koshi"));
//        englishAuthors.add(new AuthorClass("bna_mjwd", "Mahmoud Ali Al-Banna (Mujawwad)"));
        englishAuthors.add(new AuthorClass("taher", "Shirazad Taher"));
        englishAuthors.add(new AuthorClass("tblawi", "Mohammad Al-Tablaway"));
        englishAuthors.add(new AuthorClass("yahya", "Yahya Hawwa"));
        englishAuthors.add(new AuthorClass("jbrl", "Mohammed Jibreel"));
        englishAuthors.add(new AuthorClass("abkr", "Idrees Abkr"));
        englishAuthors.add(new AuthorClass("tnjy", "Khalifa Al-Tunaiji"));
        englishAuthors.add(new AuthorClass("bari", "Abdul-Bari Mohammad"));
        englishAuthors.add(new AuthorClass("jbreen", "Ibrahim Al-Jebreen"));
        englishAuthors.add(new AuthorClass("ahmad_nu", "Ahmad Nauina"));
        englishAuthors.add(new AuthorClass("mohna", "Khalid Al-Mohana"));
        englishAuthors.add(new AuthorClass("sami_dosr", "Sami Al-Dosari"));
        englishAuthors.add(new AuthorClass("trabulsi", "Ahmed Al-trabulsi"));
        englishAuthors.add(new AuthorClass("trablsi", "Ahmed Al-trabulsi (Rewayat Qalon)"));
        englishAuthors.add(new AuthorClass("bsfr", "Abdullah Basfer"));
        englishAuthors.add(new AuthorClass("jhn", "Abdullah Al-Johany"));
        englishAuthors.add(new AuthorClass("kyat", "Abdullah Khayyat"));
        englishAuthors.add(new AuthorClass("sahood", "Saleh Al-Sahood"));
        englishAuthors.add(new AuthorClass("akil", "Akhil Abdul-Hayy Rawa"));
        englishAuthors.add(new AuthorClass("mustafa", "Mustafa Ismail"));
        englishAuthors.add(new AuthorClass("braak", "Mohammed Al-Barrak"));
        englishAuthors.add(new AuthorClass("Abdullahk", "Abdullah Al-Kandari"));
        englishAuthors.add(new AuthorClass("mtrod", "Abdullah Al-Mattrod"));
        englishAuthors.add(new AuthorClass("qht", "Khaled Al-Qahtani"));
        englishAuthors.add(new AuthorClass("a_klb", "Adel Al-Kalbany"));
        englishAuthors.add(new AuthorClass("akdr", "Ibrahim Al-Akhdar"));
        englishAuthors.add(new AuthorClass("IbrahemSadan", "Ibrahim Assadan"));
        englishAuthors.add(new AuthorClass("qari", "Al-Qaria Yassen"));
        englishAuthors.add(new AuthorClass("hawashi", "Ahmad Al-Hawashi"));
        englishAuthors.add(new AuthorClass("ahmad_huth", "Ahmed Al-Huthaify"));
        englishAuthors.add(new AuthorClass("saud", "Ahmad Saud"));
        englishAuthors.add(new AuthorClass("saber", "Ahmad Saber"));
        englishAuthors.add(new AuthorClass("Aamer", "Ahmed Amer"));
        englishAuthors.add(new AuthorClass("jormy", "Ibrahim Al-Jormy"));
        englishAuthors.add(new AuthorClass("akrm", "Akram Al-Alaqmi"));
        englishAuthors.add(new AuthorClass("fateh", "Al-Fateh Al-Zubair"));
        englishAuthors.add(new AuthorClass("jaman", "Jamaan Al-Osaimi"));
        englishAuthors.add(new AuthorClass("kafi", "Khalid Abdul-Kafi"));
        englishAuthors.add(new AuthorClass("tareq", "Tareq Abdul-Ghani Daawob"));
        englishAuthors.add(new AuthorClass("jamal", "Jamal Shaker Abdullah"));
        englishAuthors.add(new AuthorClass("thubti", "Abdel-Bari Al-Toubayti"));
//        englishAuthors.add(new AuthorClass("mohsin_harthi", "Abdul-Mohsin Al-Harthy"));
        englishAuthors.add(new AuthorClass("mhsny", "Mohamed Al-Mohisni"));
        englishAuthors.add(new AuthorClass("nabil", "Nabil Al-Rifay"));
        englishAuthors.add(new AuthorClass("a_ahmed", "Abdul Aziz Al-Ahmad"));
        englishAuthors.add(new AuthorClass("kanakeri", "Abdul-Hadi Kanakeri"));
        englishAuthors.add(new AuthorClass("mrifai", "Mahmood Al-Rifai"));
        englishAuthors.add(new AuthorClass("obk", "Abdul-Mohsin Al-Obaikan"));
        englishAuthors.add(new AuthorClass("monshed", "Mohammad Al-Monshed"));
        englishAuthors.add(new AuthorClass("namh", "Neamah Al-Hassan"));
        englishAuthors.add(new AuthorClass("hani", "Hani Ar-Rifai"));
        englishAuthors.add(new AuthorClass("3zazi", "Al-Husayni Al-Azazi"));
        englishAuthors.add(new AuthorClass("qasm", "Abdul-Mohsin Al-Qasim"));
        englishAuthors.add(new AuthorClass("khan", "Mohammed Osman Khan"));
        englishAuthors.add(new AuthorClass("abdullah_dori", "Mohammad Abdul-Hakim"));
        englishAuthors.add(new AuthorClass("shaksh", "Maher Shakhashero"));
        englishAuthors.add(new AuthorClass("mzroyee", "Yasser Al-Mazroyee"));
        englishAuthors.add(new AuthorClass("muftah_thakwan", "Muftah Al-Saltany"));
        englishAuthors.add(new AuthorClass("waleed", "Waleed Al-Naehi"));
        englishAuthors.add(new AuthorClass("lahoni", "Mustafa Al-Lahoni"));
        englishAuthors.add(new AuthorClass("zaml", "Majed Al-Zamil"));
        englishAuthors.add(new AuthorClass("abo_hashim", "Ali Abu-Hashim"));
        englishAuthors.add(new AuthorClass("dokali", "Ad-dokali Mohammad Al-Alim"));
        englishAuthors.add(new AuthorClass("harthi", "Moeedh Al-Harthi"));
        englishAuthors.add(new AuthorClass("sayed", "Sayeed Ramadan"));
        englishAuthors.add(new AuthorClass("qurashi", "Yasser Al-Qurashi"));
        englishAuthors.add(new AuthorClass("brmi", "Abdullah Al-Burimi"));
        englishAuthors.add(new AuthorClass("rashad", "Mohammad Rashad Al-Shareef"));
        englishAuthors.add(new AuthorClass("yousef", "Yousef Al-Shoaey"));
        englishAuthors.add(new AuthorClass("3siri", "Ibrahim Al-Asiri"));
        englishAuthors.add(new AuthorClass("noah", "Yousef Bin Noah Ahmad"));
        englishAuthors.add(new AuthorClass("zamri", "Ustaz Zamri"));
        englishAuthors.add(new AuthorClass("zaki", "Zaki Daghistani"));
        englishAuthors.add(new AuthorClass("alzain", "Al-Zain Mohammad Ahmad"));
        englishAuthors.add(new AuthorClass("omran", "Al-Ashry Omran"));
        englishAuthors.add(new AuthorClass("hatem", "Hatem Farid Al-Waer"));
        englishAuthors.add(new AuthorClass("hamza", "Dawood Hamza"));
        englishAuthors.add(new AuthorClass("ifrad", "Rasheed Ifrad"));
        englishAuthors.add(new AuthorClass("shl", "Sahl Yassin"));
        englishAuthors.add(new AuthorClass("hkm", "Saber Abdul-Hakm"));
        englishAuthors.add(new AuthorClass("salah_hashim_m", "Salah Al-Hashim"));
        englishAuthors.add(new AuthorClass("ryan", "Adel Ryyan"));
        englishAuthors.add(new AuthorClass("wdod", "Abdul-Wadood Haneef"));
        englishAuthors.add(new AuthorClass("hajjaj", "Ali Hajjaj Al-Souissi"));
        englishAuthors.add(new AuthorClass("hafz", "Emad Hafez"));
        englishAuthors.add(new AuthorClass("lafi", "Lafi Al-Oni"));
        englishAuthors.add(new AuthorClass("shaibat", "Malik shaibat Al-Hamed"));
        englishAuthors.add(new AuthorClass("shah", "Mohammad Saleh Alim Shah"));
        englishAuthors.add(new AuthorClass("sheimy", "Mahmood Al-Sheimy"));
        englishAuthors.add(new AuthorClass("bilal", "Mousa Bilal"));
        ALL_AUTHORS_ENGLISH = Collections.unmodifiableList(englishAuthors);

        ArrayList<AuthorClass> surasArabic = new ArrayList<>();
        surasArabic.add(new AuthorClass("001", "الفاتحة"));
        surasArabic.add(new AuthorClass("002", "البقرة"));
        surasArabic.add(new AuthorClass("003", "آل عمران"));
        surasArabic.add(new AuthorClass("004", "النساء"));
        surasArabic.add(new AuthorClass("005", "المائدة"));
        surasArabic.add(new AuthorClass("006", "الأنعام"));
        surasArabic.add(new AuthorClass("007", "الأعراف"));
        surasArabic.add(new AuthorClass("008", "الأنفال"));
        surasArabic.add(new AuthorClass("009", "التوبة"));
        surasArabic.add(new AuthorClass("010", "يونس"));
        surasArabic.add(new AuthorClass("011", "هود"));
        surasArabic.add(new AuthorClass("012", "يوسف"));
        surasArabic.add(new AuthorClass("013", "الرعد"));
        surasArabic.add(new AuthorClass("014", "إبراهيم"));
        surasArabic.add(new AuthorClass("015", "الحجر"));
        surasArabic.add(new AuthorClass("016", "النحل"));
        surasArabic.add(new AuthorClass("017", "الإسراء"));
        surasArabic.add(new AuthorClass("018", "الكهف"));
        surasArabic.add(new AuthorClass("019", "مريم"));
        surasArabic.add(new AuthorClass("020", "طه"));
        surasArabic.add(new AuthorClass("021", "الأنبياء"));
        surasArabic.add(new AuthorClass("022", "الحج"));
        surasArabic.add(new AuthorClass("023", "المؤمنون"));
        surasArabic.add(new AuthorClass("024", "النور"));
        surasArabic.add(new AuthorClass("025", "الفرقان"));
        surasArabic.add(new AuthorClass("026", "الشعراء"));
        surasArabic.add(new AuthorClass("027", "النمل"));
        surasArabic.add(new AuthorClass("028", "القصص"));
        surasArabic.add(new AuthorClass("029", "العنكبوت"));
        surasArabic.add(new AuthorClass("030", "الروم"));
        surasArabic.add(new AuthorClass("031", "لقمان"));
        surasArabic.add(new AuthorClass("032", "السجدة"));
        surasArabic.add(new AuthorClass("033", "الأحزاب"));
        surasArabic.add(new AuthorClass("034", "سبأ"));
        surasArabic.add(new AuthorClass("035", "فاطر"));
        surasArabic.add(new AuthorClass("036", "يس"));
        surasArabic.add(new AuthorClass("037", "الصافات"));
        surasArabic.add(new AuthorClass("038", "ص"));
        surasArabic.add(new AuthorClass("039", "الزمر"));
        surasArabic.add(new AuthorClass("040", "غافر"));
        surasArabic.add(new AuthorClass("041", "فصلت"));
        surasArabic.add(new AuthorClass("042", "الشورى"));
        surasArabic.add(new AuthorClass("043", "الزخرف"));
        surasArabic.add(new AuthorClass("044", "الدخان"));
        surasArabic.add(new AuthorClass("045", "الجاثية"));
        surasArabic.add(new AuthorClass("046", "الأحقاف"));
        surasArabic.add(new AuthorClass("047", "محمد"));
        surasArabic.add(new AuthorClass("048", "الفتح"));
        surasArabic.add(new AuthorClass("049", "الحجرات"));
        surasArabic.add(new AuthorClass("050", "ق"));
        surasArabic.add(new AuthorClass("051", "الذاريات"));
        surasArabic.add(new AuthorClass("052", "الطور"));
        surasArabic.add(new AuthorClass("053", "النجم"));
        surasArabic.add(new AuthorClass("054", "القمر"));
        surasArabic.add(new AuthorClass("055", "الرحمن"));
        surasArabic.add(new AuthorClass("056", "الواقعة"));
        surasArabic.add(new AuthorClass("057", "الحديد"));
        surasArabic.add(new AuthorClass("058", "المجادلة"));
        surasArabic.add(new AuthorClass("059", "الحشر"));
        surasArabic.add(new AuthorClass("060", "الممتحنة"));
        surasArabic.add(new AuthorClass("061", "الصف"));
        surasArabic.add(new AuthorClass("062", "الجمعة"));
        surasArabic.add(new AuthorClass("063", "المنافقون"));
        surasArabic.add(new AuthorClass("064", "التغابن"));
        surasArabic.add(new AuthorClass("065", "الطلاق"));
        surasArabic.add(new AuthorClass("066", "التحريم"));
        surasArabic.add(new AuthorClass("067", "الملك"));
        surasArabic.add(new AuthorClass("068", "القلم"));
        surasArabic.add(new AuthorClass("069", "الحاقة"));
        surasArabic.add(new AuthorClass("070", "المعارج"));
        surasArabic.add(new AuthorClass("071", "نوح"));
        surasArabic.add(new AuthorClass("072", "الجن"));
        surasArabic.add(new AuthorClass("073", "المزمل"));
        surasArabic.add(new AuthorClass("074", "المدثر"));
        surasArabic.add(new AuthorClass("075", "القيامة"));
        surasArabic.add(new AuthorClass("076", "الإنسان"));
        surasArabic.add(new AuthorClass("077", "المرسلات"));
        surasArabic.add(new AuthorClass("078", "النبأ"));
        surasArabic.add(new AuthorClass("079", "النازعات"));
        surasArabic.add(new AuthorClass("080", "عبس"));
        surasArabic.add(new AuthorClass("081", "التكوير"));
        surasArabic.add(new AuthorClass("082", "الإنفطار"));
        surasArabic.add(new AuthorClass("083", "المطففين"));
        surasArabic.add(new AuthorClass("084", "الإنشقاق"));
        surasArabic.add(new AuthorClass("085", "البروج"));
        surasArabic.add(new AuthorClass("086", "الطارق"));
        surasArabic.add(new AuthorClass("087", "الأعلى"));
        surasArabic.add(new AuthorClass("088", "الغاشية"));
        surasArabic.add(new AuthorClass("089", "الفجر"));
        surasArabic.add(new AuthorClass("090", "البلد"));
        surasArabic.add(new AuthorClass("091", "الشمس"));
        surasArabic.add(new AuthorClass("092", "الليل"));
        surasArabic.add(new AuthorClass("093", "الضحى"));
        surasArabic.add(new AuthorClass("094", "الشرح"));
        surasArabic.add(new AuthorClass("095", "التين"));
        surasArabic.add(new AuthorClass("096", "العلق"));
        surasArabic.add(new AuthorClass("097", "القدر"));
        surasArabic.add(new AuthorClass("098", "البينة"));
        surasArabic.add(new AuthorClass("099", "الزلزلة"));
        surasArabic.add(new AuthorClass("100", "العاديات"));
        surasArabic.add(new AuthorClass("101", "القارعة"));
        surasArabic.add(new AuthorClass("102", "التكاثر"));
        surasArabic.add(new AuthorClass("103", "العصر"));
        surasArabic.add(new AuthorClass("104", "الهمزة"));
        surasArabic.add(new AuthorClass("105", "الفيل"));
        surasArabic.add(new AuthorClass("106", "قريش"));
        surasArabic.add(new AuthorClass("107", "الماعون"));
        surasArabic.add(new AuthorClass("108", "الكوثر"));
        surasArabic.add(new AuthorClass("109", "الكافرون"));
        surasArabic.add(new AuthorClass("110", "النصر"));
        surasArabic.add(new AuthorClass("111", "المسد"));
        surasArabic.add(new AuthorClass("112", "الإخلاص"));
        surasArabic.add(new AuthorClass("113", "الفلق"));
        surasArabic.add(new AuthorClass("114", "الناس"));
        ALL_SURAS_ARABIC = Collections.unmodifiableList(surasArabic);

        ArrayList<AuthorClass> surasEnglish = new ArrayList<>();
        surasEnglish.add(new AuthorClass("001", "Al-Fatihah"));
        surasEnglish.add(new AuthorClass("002", "Al-Baqarah"));
        surasEnglish.add(new AuthorClass("003", "Al-Imran"));
        surasEnglish.add(new AuthorClass("004", "An-Nisa"));
        surasEnglish.add(new AuthorClass("005", "Al-Ma'idah"));
        surasEnglish.add(new AuthorClass("006", "Al-An'am"));
        surasEnglish.add(new AuthorClass("007", "Al-A'raf"));
        surasEnglish.add(new AuthorClass("008", "Al-Anfal"));
        surasEnglish.add(new AuthorClass("009", "At-Tawbah"));
        surasEnglish.add(new AuthorClass("010", "Yunus"));
        surasEnglish.add(new AuthorClass("011", "Hud"));
        surasEnglish.add(new AuthorClass("012", "Yusuf"));
        surasEnglish.add(new AuthorClass("013", "Ar-Ra'd"));
        surasEnglish.add(new AuthorClass("014", "Ibrahim"));
        surasEnglish.add(new AuthorClass("015", "Al-Hijr"));
        surasEnglish.add(new AuthorClass("016", "An-Nahl"));
        surasEnglish.add(new AuthorClass("017", "Al-Isra"));
        surasEnglish.add(new AuthorClass("018", "Al-Kahf"));
        surasEnglish.add(new AuthorClass("019", "Maryam"));
        surasEnglish.add(new AuthorClass("020", "Taha"));
        surasEnglish.add(new AuthorClass("021", "Al-Anbiya"));
        surasEnglish.add(new AuthorClass("022", "Al-Hajj"));
        surasEnglish.add(new AuthorClass("023", "Al-Mu'minun"));
        surasEnglish.add(new AuthorClass("024", "An-Nur"));
        surasEnglish.add(new AuthorClass("025", "Al-Furqan"));
        surasEnglish.add(new AuthorClass("026", "Ash-Shu'ara"));
        surasEnglish.add(new AuthorClass("027", "An-Naml"));
        surasEnglish.add(new AuthorClass("028", "Al-Qasas"));
        surasEnglish.add(new AuthorClass("029", "Al-'Ankabut"));
        surasEnglish.add(new AuthorClass("030", "Ar-Rum"));
        surasEnglish.add(new AuthorClass("031", "Luqman"));
        surasEnglish.add(new AuthorClass("032", "As-Sajdah"));
        surasEnglish.add(new AuthorClass("033", "Al-Ahzab"));
        surasEnglish.add(new AuthorClass("034", "Saba"));
        surasEnglish.add(new AuthorClass("035", "Fatir"));
        surasEnglish.add(new AuthorClass("036", "Ya-Sin"));
        surasEnglish.add(new AuthorClass("037", "As-Saffat"));
        surasEnglish.add(new AuthorClass("038", "Sad"));
        surasEnglish.add(new AuthorClass("039", "Az-Zumar"));
        surasEnglish.add(new AuthorClass("040", "Ghafir"));
        surasEnglish.add(new AuthorClass("041", "Fussilat"));
        surasEnglish.add(new AuthorClass("042", "Ash-Shuraa"));
        surasEnglish.add(new AuthorClass("043", "Az-Zukhruf"));
        surasEnglish.add(new AuthorClass("044", "Ad-Dukhan"));
        surasEnglish.add(new AuthorClass("045", "Al-Jathiyah"));
        surasEnglish.add(new AuthorClass("046", "Al-Ahqaf"));
        surasEnglish.add(new AuthorClass("047", "Muhammad"));
        surasEnglish.add(new AuthorClass("048", "Al-Fath"));
        surasEnglish.add(new AuthorClass("049", "Al-Hujurat"));
        surasEnglish.add(new AuthorClass("050", "Qaf"));
        surasEnglish.add(new AuthorClass("051", "Adh-Dhariyat"));
        surasEnglish.add(new AuthorClass("052", "At-Tur"));
        surasEnglish.add(new AuthorClass("053", "An-Najm"));
        surasEnglish.add(new AuthorClass("054", "Al-Qamar"));
        surasEnglish.add(new AuthorClass("055", "Ar-Rahman"));
        surasEnglish.add(new AuthorClass("056", "Al-Waqi'ah"));
        surasEnglish.add(new AuthorClass("057", "Al-Hadid"));
        surasEnglish.add(new AuthorClass("058", "Al-Mujadila"));
        surasEnglish.add(new AuthorClass("059", "Al-Hashr"));
        surasEnglish.add(new AuthorClass("060", "Al-Mumtahanah"));
        surasEnglish.add(new AuthorClass("061", "As-Saf"));
        surasEnglish.add(new AuthorClass("062", "Al-Jumu'ah"));
        surasEnglish.add(new AuthorClass("063", "Al-Munafiqun"));
        surasEnglish.add(new AuthorClass("064", "At-Taghabun"));
        surasEnglish.add(new AuthorClass("065", "At-Talaq"));
        surasEnglish.add(new AuthorClass("066", "At-Tahrim"));
        surasEnglish.add(new AuthorClass("067", "Al-Mulk"));
        surasEnglish.add(new AuthorClass("068", "Al-Qalam"));
        surasEnglish.add(new AuthorClass("069", "Al-Haqqah"));
        surasEnglish.add(new AuthorClass("070", "Al-Ma'arij"));
        surasEnglish.add(new AuthorClass("071", "Nuh"));
        surasEnglish.add(new AuthorClass("072", "Al-Jinn"));
        surasEnglish.add(new AuthorClass("073", "Al-Muzzammil"));
        surasEnglish.add(new AuthorClass("074", "Al-Muddaththir"));
        surasEnglish.add(new AuthorClass("075", "Al-Qiyamah"));
        surasEnglish.add(new AuthorClass("076", "Al-Insan"));
        surasEnglish.add(new AuthorClass("077", "Al-Mursalat"));
        surasEnglish.add(new AuthorClass("078", "An-Naba"));
        surasEnglish.add(new AuthorClass("079", "An-Nazi'at"));
        surasEnglish.add(new AuthorClass("080", "'Abasa"));
        surasEnglish.add(new AuthorClass("081", "At-Takwir"));
        surasEnglish.add(new AuthorClass("082", "Al-Infitar"));
        surasEnglish.add(new AuthorClass("083", "Al-Mutaffifin"));
        surasEnglish.add(new AuthorClass("084", "Al-Inshiqaq"));
        surasEnglish.add(new AuthorClass("085", "Al-Buruj"));
        surasEnglish.add(new AuthorClass("086", "At-Tariq"));
        surasEnglish.add(new AuthorClass("087", "Al-A'la"));
        surasEnglish.add(new AuthorClass("088", "Al-Ghashiyah"));
        surasEnglish.add(new AuthorClass("089", "Al-Fajr"));
        surasEnglish.add(new AuthorClass("090", "Al-Balad"));
        surasEnglish.add(new AuthorClass("091", "Ash-Shams"));
        surasEnglish.add(new AuthorClass("092", "Al-Lail"));
        surasEnglish.add(new AuthorClass("093", "Ad-Duhaa"));
        surasEnglish.add(new AuthorClass("094", "Ash-Sharh"));
        surasEnglish.add(new AuthorClass("095", "At-Tin"));
        surasEnglish.add(new AuthorClass("096", "Al-'Alaq"));
        surasEnglish.add(new AuthorClass("097", "Al-Qadr"));
        surasEnglish.add(new AuthorClass("098", "Al-Bayyinah"));
        surasEnglish.add(new AuthorClass("099", "Az-Zalzalah"));
        surasEnglish.add(new AuthorClass("100", "Al-'Adiyat"));
        surasEnglish.add(new AuthorClass("101", "Al-Qari'ah"));
        surasEnglish.add(new AuthorClass("102", "At-Takathur"));
        surasEnglish.add(new AuthorClass("103", "Al-'Asr"));
        surasEnglish.add(new AuthorClass("104", "Al-Humazah"));
        surasEnglish.add(new AuthorClass("105", "Al-Fil"));
        surasEnglish.add(new AuthorClass("106", "Quraish"));
        surasEnglish.add(new AuthorClass("107", "Al-Ma'un"));
        surasEnglish.add(new AuthorClass("108", "Al-Kawthar"));
        surasEnglish.add(new AuthorClass("109", "Al-Kafirun"));
        surasEnglish.add(new AuthorClass("110", "An-Nasr"));
        surasEnglish.add(new AuthorClass("111", "Al-Masad"));
        surasEnglish.add(new AuthorClass("112", "Al-Ikhlas"));
        surasEnglish.add(new AuthorClass("113", "Al-Falaq"));
        surasEnglish.add(new AuthorClass("114", "An-Nas"));
        ALL_SURAS_ENGLISH = Collections.unmodifiableList(surasEnglish);
    }

    public List<AuthorClass> getAuthorList(Context context) {
        SaveSettings sv = new SaveSettings(context);
        sv.LoadData();
        return (sv.LanguageSelect == 1) ? ALL_AUTHORS_ARABIC : ALL_AUTHORS_ENGLISH;
    }

    public static void GuranAyaAsync(String ReciteName, int languageSelect, SurahListListener listener) {
        Executor executor = Executors.newSingleThreadExecutor();
        Handler handler = new Handler(Looper.getMainLooper());

        executor.execute(() -> {
            List<AuthorClass> baseList = (languageSelect == 1) ? ALL_SURAS_ARABIC : ALL_SURAS_ENGLISH;
            ArrayList<AuthorClass> resultList = new ArrayList<>();

            for (AuthorClass ac : baseList) {
                try {
                    String sdPath = Environment.getExternalStorageDirectory().getPath() + "/";
                    String ayaPath = sdPath + ReciteName + ac.ServerName + ".mp3";
                    File myFile = new File(ayaPath);

                    if (myFile.exists()) {
                        resultList.add(new AuthorClass(ac.ServerName, ac.RealName, getAvailableStatus(languageSelect), ayaPath));
                    } else {
                        String serverUrl = "https://server" + serverNumber(ReciteName) + ".mp3quran.net/" + ReciteName + "/" + ac.ServerName + ".mp3";
                        resultList.add(new AuthorClass(ac.ServerName, ac.RealName, getOnlineStatus(languageSelect), serverUrl));
                    }
                } catch (Exception ex) {
                    // It's good practice to log the error
                }
            }
            handler.post(() -> listener.onSurahListReady(resultList));
        });
    }

    public static String getAvailableStatus(int languageSelect) {
        return (languageSelect == 1) ? "من الهاتف" : "From phone";
    }

    public static String getOnlineStatus(int languageSelect) {
        return (languageSelect == 1) ? "بث مباشر" : "online";
    }

    public static String serverNumber(String EnglishName) {
        String ArabicName = "11";
        if (EnglishName.endsWith("shatri")) ArabicName = "11";

        if (EnglishName.endsWith("nufais/Rewayat-Hafs-A-n-Assem")) ArabicName = "16";
        if (EnglishName.endsWith("shaheen/Rewayat-Hafs-A-n-Assem")) ArabicName = "16";
        if (EnglishName.endsWith("shamsan/Rewayat-Hafs-A-n-Assem")) ArabicName = "14";
        if (EnglishName.endsWith("a_maasaraawi/Rewayat-Hafs-A-n-Assem")) ArabicName = "16";
        if (EnglishName.endsWith("islam/Rewayat-Hafs-A-n-Assem")) ArabicName = "14";
        if (EnglishName.endsWith("kurdi")) ArabicName = "6";
        if (EnglishName.endsWith("wdee3")) ArabicName = "6";
        if (EnglishName.endsWith("hazza")) ArabicName = "11";



        if (EnglishName.endsWith("ahmad_huth")) ArabicName = "8";
        if (EnglishName.endsWith("hawashi")) ArabicName = "11";
        if (EnglishName.endsWith("trabulsi")) ArabicName = "10";
        if (EnglishName.endsWith("ajm")) ArabicName = "10";
        if (EnglishName.endsWith("trablsi")) ArabicName = "10";
        if (EnglishName.endsWith("saud")) ArabicName = "11";
        if (EnglishName.endsWith("saber")) ArabicName = "8";
        if (EnglishName.endsWith("Aamer")) ArabicName = "10";
        if (EnglishName.endsWith("ahmad_nu")) ArabicName = "11";
        if (EnglishName.endsWith("akil")) ArabicName = "12";
        if (EnglishName.endsWith("akrm")) ArabicName = "9";
        if (EnglishName.endsWith("akdr")) ArabicName = "6";
        if (EnglishName.endsWith("IbrahemSadan")) ArabicName = "10";
        if (EnglishName.endsWith("abkr")) ArabicName = "6";
        if (EnglishName.endsWith("jbreen")) ArabicName = "6";
        if (EnglishName.endsWith("jormy")) ArabicName = "11";
        if (EnglishName.endsWith("ibrahim_dosri_warsh")) ArabicName = "10";
        if (EnglishName.endsWith("3siri")) ArabicName = "6";
        if (EnglishName.endsWith("zamri")) ArabicName = "12";
        if (EnglishName.endsWith("3zazi")) ArabicName = "8";
        if (EnglishName.endsWith("dokali")) ArabicName = "7";
        if (EnglishName.endsWith("alzain")) ArabicName = "9";
        if (EnglishName.endsWith("omran")) ArabicName = "9";
        if (EnglishName.endsWith("koshi")) ArabicName = "11";
        if (EnglishName.endsWith("fateh")) ArabicName = "6";
        if (EnglishName.endsWith("qari")) ArabicName = "11";
        if (EnglishName.endsWith("twfeeq")) ArabicName = "6";
        if (EnglishName.endsWith("jamal")) ArabicName = "6";
        if (EnglishName.endsWith("jaman")) ArabicName = "6";
        if (EnglishName.endsWith("hatem")) ArabicName = "11";
        if (EnglishName.endsWith("qht")) ArabicName = "10";
        if (EnglishName.endsWith("mohna")) ArabicName = "11";
        if (EnglishName.endsWith("kafi")) ArabicName = "11";
        if (EnglishName.endsWith("tnjy")) ArabicName = "12";
        if (EnglishName.endsWith("hamza")) ArabicName = "9";
        if (EnglishName.endsWith("ifrad")) ArabicName = "12";
        if (EnglishName.endsWith("zaki")) ArabicName = "9";
        if (EnglishName.endsWith("sami_dosr")) ArabicName = "8";
        if (EnglishName.endsWith("s_gmd")) ArabicName = "7";
        if (EnglishName.endsWith("shur")) ArabicName = "7";
        if (EnglishName.endsWith("shl")) ArabicName = "6";
        if (EnglishName.endsWith("sayed")) ArabicName = "12";
        if (EnglishName.endsWith("taher")) ArabicName = "12";
        if (EnglishName.endsWith("hkm")) ArabicName = "12";
        if (EnglishName.endsWith("sahood")) ArabicName = "8";
        if (EnglishName.endsWith("s_bud")) ArabicName = "6";
        if (EnglishName.endsWith("salah_hashim_m")) ArabicName = "12";
        if (EnglishName.endsWith("bu_khtr")) ArabicName = "8";
        if (EnglishName.endsWith("tareq")) ArabicName = "10";
        if (EnglishName.endsWith("a_klb")) ArabicName = "8";
        if (EnglishName.endsWith("ryan")) ArabicName = "8";
        if (EnglishName.endsWith("thubti")) ArabicName = "6";
        if (EnglishName.endsWith("bari")) ArabicName = "12";
        if (EnglishName.endsWith("bari_molm")) ArabicName = "10";
        if (EnglishName.endsWith("basit")) ArabicName = "7";
        if (EnglishName.endsWith("basit_warsh")) ArabicName = "10";
        if (EnglishName.endsWith("basit_mjwd")) ArabicName = "13";
        if (EnglishName.endsWith("sds")) ArabicName = "11";
        if (EnglishName.endsWith("soufi_klf")) ArabicName = "9";
        if (EnglishName.endsWith("soufi")) ArabicName = "9";
        if (EnglishName.endsWith("a_ahmed")) ArabicName = "11";
        if (EnglishName.endsWith("brmi")) ArabicName = "8";
        if (EnglishName.endsWith("Abdullahk")) ArabicName = "10";
        if (EnglishName.endsWith("mtrod")) ArabicName = "8";
        if (EnglishName.endsWith("bsfr")) ArabicName = "6";
        if (EnglishName.endsWith("kyat")) ArabicName = "12";
        if (EnglishName.endsWith("jhn")) ArabicName = "13";
        if (EnglishName.endsWith("mohsin_harthi")) ArabicName = "6";
        if (EnglishName.endsWith("obk")) ArabicName = "12";
        if (EnglishName.endsWith("qasm")) ArabicName = "8";
        if (EnglishName.endsWith("kanakeri")) ArabicName = "6";
        if (EnglishName.endsWith("wdod")) ArabicName = "8";
        if (EnglishName.endsWith("abo_hashim")) ArabicName = "9";
        if (EnglishName.endsWith("huthifi_qalon")) ArabicName = "9";
        if (EnglishName.endsWith("hthfi")) ArabicName = "9";
        if (EnglishName.endsWith("a_jbr")) ArabicName = "11";
        if (EnglishName.endsWith("hajjaj")) ArabicName = "9";
        if (EnglishName.endsWith("hafz")) ArabicName = "6";
        if (EnglishName.endsWith("frs_a")) ArabicName = "8";
        if (EnglishName.endsWith("lafi")) ArabicName = "6";
        if (EnglishName.endsWith("zaml")) ArabicName = "9";
        if (EnglishName.endsWith("shaibat")) ArabicName = "9";
        if (EnglishName.endsWith("maher_m")) ArabicName = "12";
        if (EnglishName.endsWith("maher")) ArabicName = "12";
        if (EnglishName.endsWith("shaksh")) ArabicName = "10";
        if (EnglishName.endsWith("ayyub")) ArabicName = "8";
        if (EnglishName.endsWith("braak")) ArabicName = "13";
        if (EnglishName.endsWith("tblawi")) ArabicName = "12";
        if (EnglishName.endsWith("mhsny")) ArabicName = "11";
        if (EnglishName.endsWith("monshed")) ArabicName = "10";
        if (EnglishName.endsWith("jbrl")) ArabicName = "8";
        if (EnglishName.endsWith("rashad")) ArabicName = "10";
        if (EnglishName.endsWith("shah")) ArabicName = "12";
        if (EnglishName.endsWith("minsh")) ArabicName = "10";
        if (EnglishName.endsWith("minsh_mjwd")) ArabicName = "11";
        if (EnglishName.endsWith("abdullah_dori")) ArabicName = "12";
        if (EnglishName.endsWith("khan")) ArabicName = "6";
        if (EnglishName.endsWith("mrifai")) ArabicName = "11";
        if (EnglishName.endsWith("sheimy")) ArabicName = "10";
        if (EnglishName.endsWith("husr")) ArabicName = "13";
        if (EnglishName.endsWith("bna_mjwd")) ArabicName = "8";
        if (EnglishName.endsWith("afs")) ArabicName = "8";
        if (EnglishName.endsWith("mustafa")) ArabicName = "8";
        if (EnglishName.endsWith("lahoni")) ArabicName = "6";
        if (EnglishName.endsWith("ra3ad")) ArabicName = "8";
        if (EnglishName.endsWith("harthi")) ArabicName = "8";
        if (EnglishName.endsWith("muftah_thakwan")) ArabicName = "11";
        if (EnglishName.endsWith("bilal")) ArabicName = "11";
        if (EnglishName.endsWith("qtm")) ArabicName = "6";
        if (EnglishName.endsWith("nabil")) ArabicName = "9";
        if (EnglishName.endsWith("namh")) ArabicName = "8";
        if (EnglishName.endsWith("hani")) ArabicName = "8";
        if (EnglishName.endsWith("waleed")) ArabicName = "9";
        if (EnglishName.endsWith("yasser")) ArabicName = "11";
        if (EnglishName.endsWith("qurashi")) ArabicName = "9";
        if (EnglishName.endsWith("mzroyee")) ArabicName = "9";
        if (EnglishName.endsWith("yahya")) ArabicName = "12";
        if (EnglishName.endsWith("yousef")) ArabicName = "9";
        if (EnglishName.endsWith("noah")) ArabicName = "8";
        if (EnglishName.endsWith("omar_warsh")) ArabicName = "9";
        return ArabicName;
    }
}
